{
 "title": "gf_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "Info Data", "type": "table" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "Info Data", "type": "table" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 13, "y": 1 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "Info Data", "type": "table" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "Info Data", "type": "table" }
   ]
  },
  { "title": "Friends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Mybigpoint Friends",
   "type": "table",
   "description": "All friends I have in mybigpoint",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "targets": [
    { "target": "Friends Data", "type": "table" }
   ]
  },
  { "title": "Results Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Race Position",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 3, "y": 11 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "Profile Data", "type": "table" }
   ]
  },
  {
   "title": "LK",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 11 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "Profile Data", "type": "table" }
   ]
  },
  {
   "title": "Race Points",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 11 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "Profile Data", "type": "table" }
   ]
  },
  {
   "title": "Singles Season",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "Profile Data", "type": "table" }
   ]
  },
  {
   "title": "Singles Career",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 13 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "Profile Data", "type": "table" }
   ]
  },
  {
   "title": "Singles Home Career",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "Profile Data", "type": "table" }
   ]
  },
  {
   "title": "Singles Tiebreak Season",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 13 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "Profile Data", "type": "table" }
   ]
  },
  {
   "title": "Singles Tiebreak Career",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "Profile Data", "type": "table" }
   ]
  },
  {
   "title": "Singles MT Career",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 15 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "Profile Data", "type": "table" }
   ]
  },
  {
   "title": "Singles MT Season",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 15 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "Profile Data", "type": "table" }
   ]
  },
  {
   "title": "Doubles Career",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 15 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "Profile Data", "type": "table" }
   ]
  },
  {
   "title": "Doubles Season",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 9, "y": 17 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "Profile Data", "type": "table" }
   ]
  },
  { "title": "Detailed Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Detailed Results Table",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    { "target": "LK Data", "type": "table" }
   ]
  }
 ]
}